#cloud-config
autoinstall:
    interactive-sections:
    identity:
        realname: 'Vinicius Maia'
        hostname: ubuntu
        username: vinicius
        password: '$y$j9T$cG75EBwKhZwYBbZ7owrbN0$C/DrUfpjXE7qr2uOSkoCmAgZsYMEVOuIGGN/2ItoDs1'
    locale: en_US.UTF-8
    keyboard:
        layout: br
        model: pc105
        variant: thinkpad
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
